### ISSUE TITLE
path in "Proxy's Request after hooks" wrong

### ISSUE THREAD

**Issue by v-init-h** [SolidWallOfCode/txn_box#71]
sample curl:
```
curl -D - -o /dev/null https://foo-test.yahoo.com/bar/creative-service-apac/xyz
```
remap:
```
map https://foo-test.yahoo.com/     https://www.yahoo.com/  @plugin=txn_box.so      @pparam=foo-test
```
foo-test:
```
- when: proxy-req
  do:
  - with: proxy-req-field<x-acookie-fields>
    select:
    - any-of:
      - contains: "C_WOEID=23424977"
      do: 
      - proxy-req-path: "/bar/creative-service-america/xyz" 
```
Debug shows (incorrect):
```
+++++++++ Proxy's Request after hooks +++++++++
-- State Machine Id: 26598
GET /bar/creative-service-apac/xyz HTTP/1.1 
```
whereas squid.log shows (correct):
```
origin_url=https://www.yahoo.com/bar/creative-service-america/xyz 
```

Unsure if it's a txn_box issue or ATS core
