### ISSUE TITLE
Vanish ip-space colum. 

### ISSUE THREAD

**Issue by brbzull0** [SolidWallOfCode/txn_box#78]
Not directly related with the crash, probably this should be a different issue, but as it's around a similar area.
```yaml
    - when: proxy-rsp
      do:
      - with: ua-req-field<addr>
        select:
        - is-null:
        - otherwise:
          do:
          - var<a>: [ ua-req-field<addr>, { as-ip-addr: }, { ip-space<acl>: ip-col<access> } ]
          - debug: "Var: {var<a>}"
```
The ip-space is loaded at `post-load`

Now,  if you start TS and start sending requests then you will see:
```
[Mar 16 15:33:07.369] [ET_NET 1] DIAG: (txn_box) Var: secure
...
```
if you touch the remap.config and reload ats (traffic_ctl config reload) nothing happens, or at least it's not visible.  Then you reload the txn_box global configuration (taffic_ctl plugin msg txn_box.reload x) and at  this moment you see that the value for the var is gone.
```
[ET_NET 1] DIAG: (txn_box) Var: 
[ET_NET 1] DIAG: (txn_box) Var: 
...
```
Then if you touch and reload the remap.config you will start seeing again the `var` value again.
```
 [ET_NET 1] DIAG: (txn_box) Var: secure
 [ET_NET 1] DIAG: (txn_box) Var: secure
...
```
It looks like we are missing the update of some of the shared structures.
