### ISSUE TITLE
No errors when text-block-define is unable to read the file

### ISSUE THREAD

**Issue by ywkaras** [SolidWallOfCode/txn_box#90]
& worse, when a request comes through using that text-block, it doesn't even inject anything!!!

Example:
```
-rwx------ 1 vinithb users 5 Nov 23 23:41 /home/y/conf/trafficserver/ssl/athenz/mail.backend.jedi.jws.acl_jedi.acl.token.atz.jws.ycpi.yahoo.jwt 
 ```
```
    - text-block-define:
        name: "JWT-mail_cloud-mail.backend.jedi.jws.acl_jedi.acl.token.atz.jws.ycpi.yahoo.jwt"
        path: "/home/y/conf/trafficserver/ssl/athenz/mail.backend.jedi.jws.acl_jedi.acl.token.atz.jws.ycpi.yahoo.jwt"
        duration: "1m" 
``` 
Expectation:
Since this is a per-remap plugin, ATS can't fatal but at a minimum, we need an entry in diags/error.log and/or 502 the request.

Found by Yahoo YCPI (Vineeth Bindiganavale).  Internal Yahoo issue ID:  YTSATS-4083.

This issue was probably seen in 0.4.10 .
